### ISSUE TITLE
请问消费线程数 在哪可以配置

### ISSUE THREAD

**Issue by panbdun** [aliyun/aliyun-log-consumer-java#1]
请问消费线程数 在哪可以配置

**Comment by liketic** [comment]
@zy198804065 现在没有线程数这个设置。你可以创建多个ClientWorker实例，每个worker内有一个不限制大小的线程池，线程池的大小和这个worker分配到的shard个数有关。参考sample：https://github.com/aliyun/aliyun-log-consumer-java/blob/0f0419606441194d0af539766cd2ee96eb563739/src/test/java/ClientWorkerTest.java#L6

**Comment by panbdun** [comment]
> 每个worker内有一个不限制大小的线程池,线程池的大小和这个worker分配到的shard个数有关
,我测试时也发现正如你所说，消费线程只成分配的shard个数一致，那我能理解成如果大并发不会导致我的消费端出现问题么？我对那个不限制大小的线程池比较敏感，如果 我自己在ILogHubProcessor实现加入多线程处理就相当等于把流量引入到消费端了， 自己得控制消费不了的情况了吧！

**Comment by liketic** [comment]
你是希望控制这个线程池的大小？是因为消费太慢了吗？现在的实现不支持单个shard多线程消费，所以一个shard最多一个线程。

消费不了的情况是说消费速度跟不上处理速度吗？

**Comment by panbdun** [comment]
> 你是希望控制这个线程池的大小？是因为消费太慢了吗？现在的实现不支持单个shard多线程消费，所以一个shard最多一个线程。
> 
> 消费不了的情况是说消费速度跟不上处理速度吗？

嗯。是的。现在量会有点大，如果只支持一个，那只能把shard调大点了
